# Generated by Django 3.1.7 on 2021-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='Email Address', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='Email Address', max_length=50),
        ),
    ]
